name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: mkdir -p build

    - name: Compile the project
      run: gcc -Iinclude -o build/main src/main.c src/module.c

    - name: Run the program (optional)
      run: ./build/main
